# Generated by Django 5.2 on 2025-04-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_blogpost_thumbail_alter_blogpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbail',
            field=models.ImageField(blank=True, upload_to='blog'),
        ),
    ]
